# Generated by Django 5.2.14 on 2026-06-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('query', 'Read-only query'), ('proposal', 'Proposed change'), ('approval', 'Approved change'), ('rejection', 'Rejected change')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('baseline', 'Dispatching baseline'), ('cpsat', 'CP-SAT solver')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feasible', models.BooleanField(default=False)),
                ('objective_value', models.IntegerField(blank=True, null=True)),
                ('horizon_start', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='plant.resource')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_gap_after_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('required_certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='plant.certification')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='plant.resource')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='plant.routing')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateTimeField()),
                ('is_aog', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='plant.routing')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('certifications', models.ManyToManyField(blank=True, related_name='workers', to='plant.certification')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='plant.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.PositiveIntegerField()),
                ('end_minute', models.PositiveIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ops', to='plant.job')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_ops', to='plant.operation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_ops', to='plant.resource')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ops', to='plant.schedule')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_ops', to='plant.worker')),
            ],
            options={
                'ordering': ['start_minute'],
            },
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('routing', 'sequence'), name='unique_operation_sequence_per_routing'),
        ),
    ]
